services:

  backend:
    build:
      context: .
      dockerfile: ./backend/.devcontainer/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/todo

  mysql:
    image: mysql:8.0-oracle
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  minio:
    image: minio/minio:RELEASE.2022-04-26T01-20-24Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data

  elasticsearch:
    image: elasticsearch:7.17.4
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  # schemaspy:

  nginx:
    image: nginx:1.20

volumes:

  mysql-data:
    driver: local

  minio-data:
    driver: local
